import pandas as pd
import matplotlib.pyplot as plt
import os

"""
Plots the evolution of angular momentum from the conserved_quantities.log file.
This script reads the log file generated by miluphcuda and creates a plot
showing the x, y, and z components of the total angular momentum over time.
The plot is saved to a file named 'angular_momentum_conservation.png'.

|L_initial - L_step| / |L_initial| vs time is also plotted to show conservation.

"""

# Load the conserved quantities log file
log_file = 'conserved_quantities.log'
if not os.path.exists(log_file):
    raise FileNotFoundError(f'Log file {log_file} not found.')
data = pd.read_csv(log_file, delim_whitespace=True, comment='#')
time = data['time']
Lx = data['Lx']
Ly = data['Ly']
Lz = data['Lz']
L_magnitude = (Lx**2 + Ly**2 + Lz**2)**0.5
L_initial = L_magnitude.iloc[0]
L_deviation = abs(L_initial - L_magnitude) / abs(L_initial)
# Create the plot
fig, ax1 = plt.subplots(figsize=(10, 6))
ax1.plot(time, Lx, label='Lx', color='r')
ax1.plot(time, Ly, label='Ly', color='g')
ax1.plot(time, Lz, label='Lz', color='b')
ax1.set_xlabel('Time (s)')
ax1.set_ylabel('Change in Angular Momentum Components', color='k')
ax2 = ax1.twinx()
ax2.plot(time, L_deviation, label='|L_initial - L_step| / |L_initial|', color='k', linestyle='--')
ax2.set_ylabel('Angular Momentum Deviation', color='k')
plt.title('Angular Momentum Conservation Over Time')
ax1.legend(loc='upper left')
ax1.grid(True)
# Save the plot to a file
output_file = 'angular_momentum_conservation.png'
plt.savefig(output_file)
print(f'Plot saved to {output_file}')
plt.close()