import pandas as pd
import matplotlib.pyplot as plt
import os

"""
Plots the evolution of angular momentum from the conserved_quantities.log file.
This script reads the log file generated by miluphcuda and creates a plot
showing the x, y, and z components of the total angular momentum over time.
The plot is saved to a file named 'angular_momentum_conservation.png'.
"""

# Define the input log file and the output plot file
log_file = 'conserved_quantities.log'
output_file = 'angular_momentum_conservation.png'
script_dir = os.path.dirname(os.path.realpath(__file__))
log_path = os.path.join(script_dir, log_file)
output_path = os.path.join(script_dir, output_file)

# Check if the log file exists
if not os.path.exists(log_path):
    print(f"Error: Log file not found at '{log_path}'")
    exit()

# Read the data using pandas. The file is space-delimited.
# The first row is the header, so we can use it for column names.
try:
    data = pd.read_csv(log_path, delim_whitespace=True)
except Exception as e:
    print(f"Error reading log file: {e}")
    exit()

# Check if the required columns exist
required_cols = ['1:time', '14:total-angular-mom[x]', '15:total-angular-mom[y]', '16:total-angular-mom[z]']
if not all(col in data.columns for col in required_cols):
    print(f"Error: Log file is missing one of the required columns: {required_cols}")
    print(f"Available columns: {data.columns.tolist()}")
    exit()

# Create the plot
plt.style.use('seaborn-v0_8-whitegrid')
fig, ax = plt.subplots(figsize=(12, 7))

# Plot each component of the angular momentum
ax.plot(data['1:time'], data['14:total-angular-mom[x]'], label='L_x', lw=2)
ax.plot(data['1:time'], data['15:total-angular-mom[y]'], label='L_y', lw=2)
ax.plot(data['1:time'], data['16:total-angular-mom[z]'], label='L_z', lw=2)

# Set titles and labels
ax.set_title('Conservation of Angular Momentum', fontsize=16)
ax.set_xlabel('Time (s)', fontsize=12)
ax.set_ylabel('Angular Momentum (kg*m^2/s)', fontsize=12)
ax.legend(fontsize=10)
ax.grid(True)

# Improve layout and save the figure
plt.tight_layout()
plt.savefig(output_path, dpi=300)

print(f"Plot saved successfully to '{output_path}'")
