import pandas as pd
import matplotlib.pyplot as plt
import os
# # 1:time 2:SPH-part-total 3:SPH-part-deactivated 4:grav.point-masses 5:total-mass 6:total-kinetic-energy 7:total-inner-energy 8:total-momentum 9:total-momentum[x] 10:total-momentum[y] 
# 11:total-momentum[z] 12:total-angular-mom 13:total-angular-mom[x] 14:total-angular-mom[y] 15:total-angular-mom[z] 16:barycenter-pos[x] 17:barycenter-pos[y] 18:barycenter-pos[z] 19:barycenter-vel[x] 20:barycenter-vel[y] 21:barycenter-vel[z]
"""
Plots the evolution of angular momentum from the conserved_quantities.log file.
This script reads the log file generated by miluphcuda and creates a plot
showing the x, y, and z components of the total angular momentum over time.
The plot is saved to a file named 'angular_momentum_conservation.png'.

|L_initial - L_step| / |L_initial| vs time is also plotted to show conservation.

"""

# Load the conserved quantities log file
log_file = 'conserved_quantities.log'
if not os.path.exists(log_file):
    raise FileNotFoundError(f'Log file {log_file} not found.')
column_names = [
    "time", "SPH-part-total", "SPH-part-deactivated", "grav.point-masses", "total-mass",
    "total-kinetic-energy", "total-inner-energy", "total-momentum", "total-momentum[x]", "total-momentum[y]", "total-momentum[z]",
    "total-angular-mom", "total-angular-mom[x]", "total-angular-mom[y]", "total-angular-mom[z]",
    "barycenter-pos[x]", "barycenter-pos[y]", "barycenter-pos[z]",
    "barycenter-vel[x]", "barycenter-vel[y]", "barycenter-vel[z]"
]
data = pd.read_csv(log_file, sep='\s+', comment='#', names=column_names)
time = data['time']
Lx = data['total-angular-mom[x]']
Ly = data['total-angular-mom[y]']
Lz = data['total-angular-mom[z]']
L_magnitude = (Lx**2 + Ly**2 + Lz**2)**0.5
L_initial = L_magnitude.iloc[1]
L_deviation = abs(L_initial - L_magnitude) / abs(L_initial)
# Create the plot
fig, ax1 = plt.subplots(figsize=(10, 6))
ax1.plot(time, L_deviation, label='|L_initial - L_step| / |L_initial|')
ax1.set_ylabel('Angular Momentum Deviation', color='k')
plt.title('Angular Momentum Conservation Over Time')
ax1.legend()
ax1.grid(True)
# Save the plot to a file
output_file = 'angular_momentum_conservation.png'
plt.savefig(output_file)
print(f'Plot saved to {output_file}')
plt.close()